

from mtcnn.exceptions.invalid_image import InvalidImage
